version: "3.8"
services:
  app:
    image: zdrave893/petshop-app:31-01-2025-18-39-c3130-master
    container_name: petshop-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - MONGO_URI=mongodb://mongo:27017/petshopdb
    depends_on:
      - mongo
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 20s
      timeout: 5s
      retries: 3
      

  mongo:
    image: zdrave893/petshop-app:31-01-2025-18-39-c3130-master
    container_name: petshop-mongo
    volumes:
      - petshop_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
volumes:
  petshop_data: