# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: petshop-db-init
#   namespace: petshop
# spec:
#   template:
#     spec:
#       containers:
#         - name: petshop-db
#           image: mongo:4.4
#           command: ["/bin/sh", "-c"]
#           args:
#             - |
#               sleep 30 &&
#               mongo --host petshop-db-0.petshop-db-headless.petshop.svc.cluster.local --eval '
#               rs.initiate({
#                 _id: "rs0",
#                 members: [
#                   { _id: 0, host: "petshop-db-0.petshop-db-headless.petshop.svc.cluster.local:27017" },
#                   { _id: 1, host: "petshop-db-1.petshop-db-headless.petshop.svc.cluster.local:27017" },
#                   { _id: 2, host: "petshop-db-2.petshop-db-headless.petshop.svc.cluster.local:27017" },
#                 ]
#               });
#               '
#       restartPolicy: OnFailure

apiVersion: batch/v1
kind: Job
metadata:
  name: petshop-db-replicas-init
  namespace: petshop
spec:
  template:
    spec:
      containers:
        - name: petshop-db-replicas-init
          image: mongo:4.4
          command: ["/bin/sh", "-c"]
          args:
            - >
              sleep 30 && mongo --host petshop-db-0.petshop-db-headless.petshop.svc.cluster.local --eval '
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "petshop-db-0.petshop-db-headless.petshop.svc.cluster.local:27017" },
                  { _id: 1, host: "petshop-db-1.petshop-db-headless.petshop.svc.cluster.local:27017" },
                  { _id: 2, host: "petshop-db-2.petshop-db-headless.petshop.svc.cluster.local:27017" }
                ]
              });
              '
      restartPolicy: OnFailure
