apiVersion: v1
kind: ConfigMap
metadata:
  name: petshop-app-configmap
  namespace: petshop
data:
  FLASK_APP: app.py
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: "5000"
  FLASK_ENV: development
  FLASK_DEBUG: "1"
  MONGO_URI: "mongodb://petshop-db-0.petshop-db-headless.petshop.svc.cluster.local:27017,petshop-db-1.petshop-db-headless.petshop.svc.cluster.local:27017,petshop-db-2.petshop-db-headless.petshop.svc.cluster.local:27017/petshop-db?replicaSet=rs0"
