name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Build Version
        id: versioning
        run: |
          DATE=$(date +%d-%m-%Y-%H-%M)
          SHORT_SHA=${GITHUB_SHA::5}
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          VERSION="${DATE}-${SHORT_SHA}-${BRANCH}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Generated Version: $VERSION"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t zdrave893/petshop-app:${{ env.VERSION }} .

      - name: Push Docker Image
        run: docker push zdrave893/petshop-app:${{ env.VERSION }}

      - name: Update Kubernetes and Docker Compose with New Image Version
        run: |
          sed -i "s|image: .*|image: ${{secrets.DOCKER_USERNAME}}/petshop-app:${{ env.VERSION }}|" kubernetes/petshop-deployment.yaml
          sed -i "s|image: .*|image: ${{secrets.DOCKER_USERNAME}}/petshop-app:${{ env.VERSION }}|" docker-compose.yml
          
          git config --global user.email "107679981+zdrave123@users.noreply.github.com"
          git config --global user.name "zdrave123"
          
          git add kubernetes/petshop-deployment.yaml
          git add docker-compose.yml
          
          PREVIOUS_COMMIT=$(git log -1 --skip 1 --pretty=%B)
          git commit -m "Updated image version to: ${{ env.VERSION }}"
          git push

          sleep 10
