name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Build Version
        id: versioning
        run: |
          DATE=$(date +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          VERSION="${DATE}-${SHORT_SHA}-${BRANCH}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" > .env
          echo "Generated Version: $VERSION"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t zdrave893/petshop-app:${{ env.VERSION }} .

      - name: Push Docker Image
        run: docker push zdrave893/petshop-app:${{ env.VERSION }}

      - name: Save .env File
        run: |
          echo "Saving .env file with VERSION=$VERSION"
          cat .env